label sleeping_label():
    "The soft glow of the moonlight spills in through [the_person.title]'s bedroom window, casting an ethereal light across her sleeping form." 
    "She stirs restlessly beneath the covers, tossing and turning as if caught in a dreamy haze."
    "It isn't until she lets out a quiet moan that you realise what's really going on: she's playing with herself."
    "Your heart races as you watch; unable to tear your gaze away from the sight before you."
    if temp_top:
        "Her hand slides slowly up underneath her [.display_name], fingers seeking out the warmth between her legs."
    "With practiced ease, she parts her folds and begins to stroke herself; gentle at first but soon growing more urgent as pleasure builds within her."
    "Her breath comes faster now, shallower and ragged against the silence of the room."
    "You can see beads of sweat forming along her brow despite the cool air wafting in from the open window."
    "Each time her hips buck into her touch, it feels like you're being thrust right there alongside her."
    "Your own cock throbs painfully in response, aching for release."
    "[the_person.title]'s cries fill the space around her now; muffled by pillows but no less intense for it."
    "They echo through your body like a siren song; drawing you closer even as they drive you wild with need."
    "As she nears climax, her movements become frantic; nails digging into the sheets as she tries desperately not to make too much noise lest someone hear her."
    "And then finally - with a shuddering cry that seems to come straight from deep within her soul - she explodes: muscles tensing, eyes rolling back in her head, every fiber of her being consumed by ecstasy."

    "You sit transfixed by the screen, watching as [the_person.title] lies in bed, eyes closed and hands resting lightly on her stomach."
    "In the dimly lit room, the only source of illumination comes from the soft glow of her phone, casting eerie shadows across her features."
    "Yet despite the darkness, you can sense her energy, her passion, and her desire."
    "She starts by rubbing her clit gently, her fingers dancing across its sensitive surface."
    "Her moans are low and steady, a rhythmic accompaniment to her ministrations."
    "Then, without warning, she inserts a small vibrator into her dripping folds, her face contorting into a mixture of pleasure and discomfort as she adjusts to the novel sensation."
    "You watch as she experiments with different speeds and patterns, her reactions visceral and raw."
    "Each time she finds something that tickles her fancy, her hips buck wildly, her legs kicking out in response to the electric current flowing through her veins."
    "The image before you is nothing short of captivating, and yet there's something undeniably alluring about the way she remains completely unaware of your presence."
    "As the night wears on, [the_person.title] becomes bolder, exploring her limits with reckless abandon."
    "The sounds of her pleasure grow louder, her gasps and whimpers intermingling with the faint rustle of sheets as she writhes beneath the covers."
    "Despite being unable to see her face, you can tell by the intensity of her moans that she's reaching new heights of ecstasy."
    "And then, suddenly, it ends. Her movements cease, replaced by the gentle rise and fall of her chest as she catches her breath."
    "Exhausted but exhilarated, [the_person.title] rolls onto her side, unaware of the effect she's had on you."
    "You can feel your own arousal growing, a testament to the power of her self-pleasure and its ability to consume even from afar."
    "You know that this is only one glimpse into [the_person.title]'s hidden world; there are countless other moments like these waiting for you if you dare seek them out."
    "And although it may be forbidden, watching her in secret feels more thrilling than anything else ever could."

#The light from the camera illuminates [the_person.title]'s room just enough for you to make out her every movement, every breath. She lies there on her back, legs slightly spread and arms flung wide in invitation. Her fingers dance across her smooth skin, teasing and taunting as they explore her most intimate places.
#Her touch is gentle at first, a featherlight caress over her breast before moving lower towards her stomach and further southward still. You can see beads of sweat gathering above her upper lip as she nears her center, anticipation building with each passing moment. And then, finally, she reaches her target: her sex. Her middle finger slips inside easily, stretching her folds and seeking the bundle of nerves that lie within. With practiced ease, she begins to stroke herself; faster and harder now, eyes closed and mouth parted in pleasure.
#Your heart races along with hers, watching this forbidden act play out before your very eyes. As if sensing your presence somehow, [the_person.title] arches her back and moans loudly into the darkness, her hips bucking up off the mattress in search of release. Your cock twitches in response, achingly hard beneath your pants.
#She switches hands, using both to bring herself even greater pleasure. One hand massages her breast while the other works furiously between her legs, driving her closer and closer to orgasm. Her gasps echo through the quiet bedroom, filling the air like music. It's almost too much for you to bear, the sight of her so open and exposed yet completely unaware of your existence.
#And when it happens, when she cries out your name against unspoken lips, you feel it deep down in your core. A hot shudder runs through your body as you witness her release, helpless to do anything but watch and bask in the afterglow. Finally, spent and satisfied, she rolls onto her side, breathing heavily as if running a marathon. You can't help but wonder what other secrets she keeps hidden beneath those sheets…

#[the_person.title] tosses and turns restlessly in her bed, her body aching for release. The sheets twist around her legs as she squirms beneath them, the fabric a constant reminder of what it is that she craves but cannot have. She's so close to giving in, letting herself succumb to the need building inside her. But something holds her back; fear or shame perhaps.
#Her hands drift lower, tracing circles over her stomach before dipping below the waistband of her pajama bottoms. You can almost feel the heat emanating from between her thighs as you watch her fingers tease and tease again. Each time they graze against sensitive skin, your own cock throbs with desire. It's clear that [the_person.title] isn't quite ready yet, not fully comfortable enough with this newfound wantonness within herself.
#She rolls onto her side, curling into a ball and pressing her forehead against the pillow. Her breath comes fast and shallow now, each exhale sending shivers through her frame. With every passing moment, tension builds like a spring wound too tightly. Finally, unable to take anymore, she reaches downward once more, slips two fingers deep inside, only to pull away just as quickly. The frustration etched on her face mirrors yours.
#The camera captures it all: the hesitation, the longing, the eventual surrender. As if drawn by some invisible force, those same fingers return, this time moving faster and firmer. Your heart pounds wildly in your chest, urging her on even as your mind begs for silence. Her hips buck up off the mattress involuntarily at the sensation, her gasps filling the room and driving you wild. It's agony watching her deny herself this simple pleasure, but the wait seems interminable.
#Finally, with one last gasp, she gives in. Her fingers find their mark, releasing an explosion of pleasure that reverberates throughout the entire house. Her body convulses violently, limbs flailing as she rides out the wave of ecstasy. Even though you know she doesn't realise it, you can't help but feel a sense of triumph in having been able to share in this most private of moments.
#As the intensity fades, leaving behind nothing but contentment and satisfaction, [the_person.title] collapses back onto her pillow, already dreaming of another chance to satisfy her desires. And as you watch her slip back into slumber, you can't help but imagine what tomorrow might hold – and how you might be able to guide her toward fulfilling these secret yearnings of hers…

#In her fitful slumber, [the_person.title]'s body twists and turns beneath the sheets. Her breath comes in ragged gasps as she thrashes about on the bed, unable to find a comfortable position. The thin fabric of her pajamas does little to conceal anything from your hungry eyes; each time she rolls onto her side or stretches out an arm above her head, you catch another glimpse of smooth skin, flushed with heat.
#Her breasts are thrust forward enticingly, nipples hardening into tight buds that peak through the material. You can almost see them beckoning for your touch, begging for release. As she tosses and turns, one pale thigh is briefly exposed, muscles tensing and relaxing rhythmically underneath soft skin. Even in sleep, there's something so alluring about how unaware she seems - how completely at peace with being exposed like this.
#[the_person.title] moans softly in her dreams, arching her back off the mattress before collapsing limply once more. A trail of saliva dangles precariously from her lips, shimmering in the dim light cast by the moon outside her window. Each tiny movement causes her bottom lip to slide across her teeth, drawing your gaze downward toward where it disappears between her parted lips. You wonder what sort of erotic fantasy could be playing out inside her mind right now…

#[the_person.title] lies naked beneath the sheets, her body bare and vulnerable except for the thin strip of cotton covering her most intimate parts. In her sleep, she writhes and squirms, her movements chaotic and uncontrolled. Everywhere you look, there's evidence of her passion, her desire burning hotter than ever despite the late hour.
#You study her closely, admiring the way her curves shift and undulate beneath the fabric of her panties. They ride low on her hips, exposing the gentle swell of her belly and the delicate arc of her hipbones. The lace trim along the edges of the garment accents her femininity, emphasizing the fullness of her thighs and the soft roundness of her ass.
#Her arms are thrown overhead, her fingers clenching and unclenching spasmodically as she struggles to find comfort in her slumber. The veins in her forearms stand out sharply, pulsing with each beat of her heart. Her neck is exposed, the tendons flexing and relaxing as she moves, revealing the faint trace of a birthmark near her shoulder blade – a small, hidden treasure that you've always found utterly irresistible.
#Even in her sleep, [the_person.title]'s beauty is undeniable. There's something enchanting about seeing her so vulnerable, so exposed – knowing that no matter how much she tries to hide it, her innermost secrets remain laid bare for you alone to behold. It's both humbling and empowering, knowing that you possess the key to unlocking such depths of desire within her.
#And as you continue to observe her, mesmerized by her every move, you can't help but marvel at the thought of having her entirely to yourself – of waking her from these restless dreams with a single touch, a whispered promise of pleasure, and guiding her through the darkness toward the blissful dawn of your shared love.

#[the_person.title] lies still, her breathing slow and steady as she drifts peacefully through the depths of slumber. Her features are relaxed, serene even in repose; each curve and contour of her body flowing seamlessly into the next like a sculpture carved from the purest marble. The only sign that she's alive at all is the rise and fall of her chest beneath the sheets, a gentle testament to the power of life within her.
#Her hair spreads out around her head like a halo of darkness, obscuring any hint of exhaustion or stress from earlier in the day. Even in sleep, there's an ethereal quality about her that makes you feel as though she might vanish if you were to breathe too heavily in her direction. It's both entrancing and disarming, this sense of fragility combined with inner strength.
#She wears nothing but a thin cotton t-shirt now, its hem riding up slightly above her navel to reveal the smooth expanse of her flat stomach. Your gaze travels lower still, drawn irresistibly toward the V-neckline where it dips between her full breasts. You can just make out the outline of her nipples, hardened by cold air conditioning or perhaps desire for something more… intimate.
#The camera captures every detail with perfect clarity, as if it were designed specifically to draw you into this private moment between [the_person.title] and her dreams. And yet despite the intimacy of the scene, there's something almost surreal about watching her sleep like this; a sense that she exists in another world entirely, one where your presence doesn't matter nearly as much as the fantasies that dance through her head while she's unconscious.

#[the_person.title] lies naked beneath the sheets, her body exposed to your gaze. The soft glow of moonlight filters through the window and dances across her skin like a lover's touch, casting shadows that play teasingly over each curve and hollow. Her breasts rise and fall with every breath she takes, nipples tightening into firm peaks against the pale flesh.
#Her long legs are splayed invitingly apart, revealing the smooth carpet of hair between her thighs, darker than the rest of her skin but no less alluring. You can see everything about her in this moment: the way her rib cage rises and falls with each labored breath; the delicate arch of her neck as it meets the pillow; even the tiny twitches and spasms that betray occasional dream-induced movements deep within her slumber.
#She looks so peaceful here, so trusting and unaware. It makes you wonder what sort of world she must be exploring behind those closed eyelids, what vibrant colours and textures fill her mind when she slips away from reality like this. And yet there's something undeniably erotic about seeing her so vulnerable, knowing full well that you're the only one who knows where she truly is right now - safe in her bed or lost in some faraway fantasy?

#[the_person.title] lies on her side, her back arched gracefully against the pillows. She's clothed in a short silk robe that falls open to reveal the tantalizing sight of her bare legs, smooth and supple underneath the warmth of the blankets. The material of her robe pools onto the floor beside her, leaving little to the imagination save for the occasional glimpse of her toned calves and ankles as she shifts position throughout the night.
#Her long hair cascades over her shoulders, framing her face in a curtain of dark waves. A few strands have escaped their confines, falling across her forehead and temples, adding a touch of innocence to her otherwise seductive appearance. Despite the modesty of her attire, there's an undeniable sensuality to her posture that leaves little doubt as to what kind of dreams may be unfolding inside her mind.
#A slight smile plays on her lips, as if she's lost in some distant memory or vivid fantasy. Her eyebrows furrow slightly, giving away the fact that she's deep in thought – possibly replaying the events of the evening in her mind, reliving each moment of connection and desire.
#In this state of half-sleep, [the_person.title] seems to exist in a liminal space between reality and fantasy, her body and soul bared before you in a way that's both thrilling and profoundly intimate. It's as if the barriers between public and private, conscious and subconscious, have been stripped away, leaving you with an unparalleled opportunity to witness the true essence of her being.
#As you continue to observe her, you can't help but wonder what it would take to coax her from these dreams, to draw her fully into the world of wakefulness and make her feel every bit as alive as she appears in your eyes. The thought sends a shiver down your spine, leaving you aching for something more…something deeper than mere observation.

#[the_person.title]'s breasts rise and fall gently with each breath, the pale mounds of flesh contrasting beautifully against the darker hue of her skin. Her nipples are hardened into tight little peaks that stand at attention beneath her soft curls. The camera captures every detail with unflinching clarity: the delicate network of veins that web across their surface, the way they quiver slightly as she dreams, and even the tiny bead of moisture that has formed at their tips.
#She lies on her back now, one arm flung above her head while the other rests limply by her side. Her long legs are drawn up toward her chest in a fetal position, exposing the smooth expanse of stomach and hip bones below. Even in sleep, there's an air of confidence about her; it seems almost impossible for her to appear anything less than perfect.
#Her face is serene, devoid of any hint of worry or stress from earlier in the day. Instead, you catch fleeting expressions of joy and desire flitting across her features as if she were caught up in some passionate dreamworld all her own. It's both thrilling and intensely arousing to witness this private side of her life unfold before your eyes without restriction or judgment.
#As you watch, it becomes increasingly difficult to resist the urge to reach out and touch her; to feel the warmth of her skin, the weight of her breasts in your hands, the softness of her lips under yours. But for now, you remain content simply to observe…to soak up every last bit of her essence through the lens of the camera until eventually, reluctantly, she slips further away from consciousness and into the depths of slumber once more.

#[the_person.title]'s perfect, nude form lies exposed before you as she sleeps soundly on her back. Her long hair fans out across the pillow behind her head like a dark halo of silk. Every curve and angle of her body is visible to your hungry gaze: the delicate arch of her neck; the gentle swell of her breasts with their rosy nipples; the flat plane of her stomach leading down to the neat triangle of curls between her legs.
#She twitches occasionally in what appears to be a dream, one hand moving upward toward her breast or hip while the other thrashes weakly at the sheets beside her. The sight sends shivers through you, heightening your arousal even further than it already was. You can practically feel yourself growing harder just from watching her so intimately.
#As if drawn by some invisible force, your eyes are irresistibly drawn lower still until they meet those of Lily, who has crept into frame unnoticed during one of [the_person.title]'s restless movements. Startled by the realisation that she's been caught spying, Lily quickly averts her gaze but not before exchanging a knowing smile with you over [the_person.title]'s sleeping form. It's clear that this isn't the first time either of you have engaged in such…activities.

